import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";

const AccessibilityBar = dynamic(
  () => import("@/components/AccessibilityBar"),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, showFooter = true }) {
  return (
    <html id="root" lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <AccessibilityBar>
            <main className="flex flex-col flex-grow dark:bg-[#1f1f1f]">
              {children}
            </main>
            {showFooter && <Footer />}
          </AccessibilityBar>
        </div>
      </body>
    </html>
  );
}
