import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const AccessibilityBar = dynamic(
  () => import("@/components/AccessibilityBar"),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html id="root" lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} >
        <main className="flex flex-col flex-grow dark:bg-[#1f1f1f]">
          {children}
        </main>
      </body>
    </html>
  );
}